# Move video rectangle
#Alt+left  add video-pan-x  0.1
#Alt+right add video-pan-x -0.1
#Alt+up    add video-pan-y  0.1
#Alt+down  add video-pan-y -0.1
# Zoom/unzoom video
#Alt++     add video-zoom   0.1
#Alt+-     add video-zoom  -0.1
# Reset video zoom/pan settings
#Alt+BS set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0

. frame-step
, frame-back-step
n     seek  5
h     seek -5
RIGHT seek  5
LEFT  seek -5
UP    seek  60
DOWN  seek -60
Ctrl+RIGHT add chapter  1
Ctrl+LEFT  add chapter -1
b revert-seek
> playlist-next
< playlist-prev
+ add speed  0.1
- add speed -0.1
1 set volume 10
2 set volume 20
3 set volume 30
4 set volume 40
5 set volume 50
6 set volume 60
7 set volume 70
8 set volume 80
9 set volume 90
0 set volume 100
m cycle mute
s cycle sub
a cycle audio
v cycle video
p no-osd cycle-values osd-level 3 1
r video-reload
l ab-loop
q quit
CLOSE_WIN quit
CLOSE_WIN {encode} quit 4
POWER quit
STOP quit
PLAY cycle pause
PAUSE cycle pause
PLAYPAUSE cycle pause
PLAYONLY set pause no
PAUSEONLY set pause yes
SPACE cycle pause
FORWARD seek 60
REWIND seek -60
NEXT playlist-next
PREV playlist-prev
VOLUME_UP add volume 2
VOLUME_DOWN add volume -2
WHEEL_UP add volume 2
WHEEL_DOWN add volume -2
MUTE cycle mute
