#!/usr/bin/bash

set -e

# done like this so I can redo folder structure without having to modify link destinations
link() {
	[ "${2%/*}" != "$2" ] && mkdir -p "${2%/*}"
	if [ "${2%/}" = "$2" ]; then
		ln -sfT "$HOME/dotfiles/dest/$1" "$HOME/$2"
	else
		ln -sfT "$HOME/dotfiles/dest/$1" "$HOME/$2${1##*/}"
	fi
}

for i in Xresources bash_profile bashrc fff inputrc profile screenrc screenrcunbind tmux.conf vim vimrc xbindkeysrc xinitrc zsh zshrc; do
	link "$i" ".$i"
done
link mutt/muttrc              .muttrc

for i in cleanup dunst herbstluftwm navi mpv neofetch pipewire; do
	link "$i" .config/
done
link qutebrowser/config.py    .config/qutebrowser/
link systemd                  .config/systemd/user

link icons                    .local/share/
link fonts                    .local/share/
link navi                     .local/share/
link qutebrowser/greasemonkey .local/share/qutebrowser/
link qutebrowser/userscripts  .local/share/qutebrowser/

link xpra                     .xpra

sudo chown root:root ~/dotfiles/bin/power
sudo chown root:root ~/dotfiles/systemd/power.service
sudo ln -sf ~/dotfiles/systemd/power.service /etc/systemd/system/
sudo systemctl enable power
sudo chown root:root ~/dotfiles/bin/{zscrub,zstatus}
sudo chown root:root ~/dotfiles/systemd/zscrub.*
command -v zfs &>/dev/null && {
	sudo ln -sf ~/dotfiles/systemd/zscrub.* /etc/systemd/system/
	sudo systemctl enable zscrub.timer
}

# git config here so I don't have to worry about accidentally pushing .gitconfig sensitive info
git config --global core.editor "vim"
git config --global core.pager "diff-so-fancy | less -x2 -RFX"
git config --global init.defaultbranch "master"
git config --global pull.rebase true
git config --global user.email "isaacelenbaas@gmail.com"
git config --global user.name "IsaacElenbaas"

~/dotfiles/terminal/terminfo

sudo bash -c 'for i in /usr/lib/python3*/site-packages/qutebrowser; do
	cd "$i" &>/dev/null
	{ [ -d "./.git" ] && [ "$(git status -s | wc -l)" = 0 ]; } && exit
	rm -rf .git
	git init &>/dev/null
	git checkout -b hint_escape_bind_fixes
	git add -A &>/dev/null
	git config user.email "isaacelenbaas@gmail.com"
	git config user.name "IsaacElenbaas"
	git commit -m "base" --no-gpg-sign &>/dev/null
	git remote add upstream https://github.com/qutebrowser/qutebrowser.git &>/dev/null
	git fetch upstream master pull/6821/head:pr/6821
	git replace --graft "$(git log upstream/master..pr/6821 --reverse --format=format:%H | head -n 1)~1"
	git checkout "$(git replace)" &>/dev/null
	git switch -c pr/6821_trimmed &>/dev/null
	git cherry-pick $(git log upstream/master..pr/6821 --reverse --format=format:%H) &>/dev/null
	FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch --subdirectory-filter qutebrowser &>/dev/null
	git checkout hint_escape_bind_fixes &>/dev/null
	git cherry-pick $(git log pr/6821_trimmed --reverse --format=format:%H | { IFS= read -r; cat; })
done'
