#!/usr/bin/bash

ln -sf /home/isaacelenbaas/dotfiles/zsh                      /home/isaacelenbaas/.zsh
ln -sf /home/isaacelenbaas/dotfiles/vim                      /home/isaacelenbaas/.vim
ln -sf /home/isaacelenbaas/dotfiles/bash_profile             /home/isaacelenbaas/.bash_profile
ln -sf /home/isaacelenbaas/dotfiles/bashrc                   /home/isaacelenbaas/.bashrc
ln -sf /home/isaacelenbaas/dotfiles/zshrc                    /home/isaacelenbaas/.zshrc
ln -sf /home/isaacelenbaas/dotfiles/inputrc                  /home/isaacelenbaas/.inputrc
ln -sf /home/isaacelenbaas/dotfiles/vimrc                    /home/isaacelenbaas/.vimrc
ln -sf /home/isaacelenbaas/dotfiles/screenrc                 /home/isaacelenbaas/.screenrc
ln -sf /home/isaacelenbaas/dotfiles/screenrcunbind           /home/isaacelenbaas/.screenrcunbind
ln -sf /home/isaacelenbaas/dotfiles/xbindkeysrc              /home/isaacelenbaas/.xbindkeysrc
ln -sf /home/isaacelenbaas/dotfiles/xinitrc                  /home/isaacelenbaas/.xinitrc
ln -sf /home/isaacelenbaas/dotfiles/Xresources               /home/isaacelenbaas/.Xresources
ln -sf /home/isaacelenbaas/dotfiles/fff                      /home/isaacelenbaas/.fff
ln -sf /home/isaacelenbaas/dotfiles/muttrc                   /home/isaacelenbaas/.muttrc

mkdir -p /home/isaacelenbaas/.config
ln -sf /home/isaacelenbaas/dotfiles/cleanup                  /home/isaacelenbaas/.config/
ln -sf /home/isaacelenbaas/dotfiles/dunst                    /home/isaacelenbaas/.config/
ln -sf /home/isaacelenbaas/dotfiles/herbstluftwm             /home/isaacelenbaas/.config/
ln -sf /home/isaacelenbaas/dotfiles/neofetch                 /home/isaacelenbaas/.config/
mkdir -p /home/isaacelenbaas/.config/mpv
ln -sf /home/isaacelenbaas/dotfiles/mpv.conf                 /home/isaacelenbaas/.config/mpv/
ln -sf /home/isaacelenbaas/dotfiles/mpvbinds.conf            /home/isaacelenbaas/.config/mpv/input.conf
mkdir -p /home/isaacelenbaas/.config/qutebrowser
ln -sf /home/isaacelenbaas/dotfiles/qutebrowser/greasemonkey /home/isaacelenbaas/.config/qutebrowser/
ln -sf /home/isaacelenbaas/dotfiles/qutebrowser/config.py    /home/isaacelenbaas/.config/qutebrowser/
mkdir -p /home/isaacelenbaas/.config/systemd
ln -sf /home/isaacelenbaas/dotfiles/systemd                  /home/isaacelenbaas/.config/systemd/user

mkdir -p /home/isaacelenbaas/.local/share
ln -sf /home/isaacelenbaas/dotfiles/icons                    /home/isaacelenbaas/.local/share/
ln -sf /home/isaacelenbaas/dotfiles/fonts                    /home/isaacelenbaas/.local/share/
mkdir -p /home/isaacelenbaas/.local/share/qutebrowser
ln -sf /home/isaacelenbaas/dotfiles/qutebrowser/greasemonkey /home/isaacelenbaas/.local/share/qutebrowser/
ln -sf /home/isaacelenbaas/dotfiles/qutebrowser/userscripts  /home/isaacelenbaas/.local/share/qutebrowser/

# git config here so I don't have to worry about accidentally pushing .gitconfig sensitive info
git config --global core.editor "vim"
git config --global core.pager "diff-so-fancy | less -x2 -RFX"
git config --global init.defaultbranch "master"
git config --global pull.rebase true
git config --global user.email "isaacelenbaas@gmail.com"
git config --global user.name "IsaacElenbaas"
