av-sync=False
desktop-scaling=off
dpi=96
# default causes issues with gaining focus
input-method=none
key-shortcut=clear
splash=False
system-tray=False
title=@title@
# add the following to /etc/xpra/xorg.conf if GPU won't unload
#Section "Module"
#  Disable "glx"
#  Disable "glamor"
#EndSection
#
#Section "OutputClass"
#  Identifier "nvidia"
#  MatchDriver "nvidia-drm"
#  Option "AllowIndirectGLXProtocol" "off"
#EndSection
