#!/bin/bash

cd ~
[ -f $sysresources ] && xrdb -merge /etc/X11/xinit/.Xresources
[ -f "$userresources" ] && xrdb -merge ~/.Xresources
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && source "$f"
	done
	unset f
fi

export QT_QPA_PLATFORMTHEME=gnome
export QT_STYLE_OVERRIDE=kvantum
export GTK_THEME=Arc-Dark # settings.ini isn't working
systemctl --user import-environment QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE GTK_THEME

# restarting here and not enabling because with my laptop I often restart X to turn on/off GPU
# all systemd units ignore xpra and run on DISPLAY due to /etc/X11/xinit/xinitrc.d/50-systemd-user.sh called above
[ -f "$HOME/.config/systemd/user/keyrepeat.service" ] && systemctl --user restart keyrepeat
[ -f "$HOME/.config/systemd/user/mocp.service" ]      && systemctl --user restart mocp
[ -f "$HOME/.config/systemd/user/unclutter.service" ] && systemctl --user restart unclutter
[ -f "$HOME/.config/systemd/user/rollbg.service" ]    && systemctl --user restart rollbg
[ -f "$HOME/.config/systemd/user/xbindkeys.service" ] && systemctl --user restart xbindkeys
[ -f "$HOME/.config/systemd/user/xbindkeys.service" ] && systemctl --user restart xsuspender
[ -f /usr/lib/systemd/user/dunst.service ]            && systemctl --user restart dunst
if modprobe --dry-run --first-time nvidia &>/dev/null; then
	systemctl --user stop --no-block moosefs-mount
	systemctl --user stop osu-keysounds
	systemctl --user stop --no-block steam
	systemctl --user stop vnc
else
	[ -f "$HOME/.config/systemd/user/moosefs-mount.service" ] && systemctl --user restart --no-block moosefs-mount
	#[ -f "$HOME/.config/systemd/user/osu-keysounds.service" ] && systemctl --user restart osu-keysounds
	[ -f "$HOME/.config/systemd/user/steam.service" ]         && systemctl --user restart --no-block steam
	[ -f "$HOME/.config/systemd/user/vnc.service" ]           && systemctl --user restart vnc
	xset s off -dpms
	qpwgraph &>/dev/null &
	easyeffects &>/dev/null &
fi
if [ -d /sys/class/power_supply/BAT0 ]; then
	{ printf "power off\nexit\n" | bluetoothctl; } &
else
	{ printf "power on\nexit\n" | bluetoothctl; } &
	xrandr --setprovideroutputsource modesetting NVIDIA-0
	xset s off -dpms
fi

systemctl is-active --user --quiet xpra-server && export XPRA_DISPLAY=":10" && systemctl --user restart xpra-client
exec herbstluftwm --locked
