#!/usr/bin/bash

hc () {
	herbstclient "$@"
}
hc emit_hook reload
hc keyunbind --all

m=$(xrandr --query | awk '/ connected/{print}' | wc -l)
h=20
Mod=Mod4 # Use the super key as the main modifier

# autostart
hc set auto_detect_monitors 0 # Required to turn off monitors with xrandr
pacwall.sh -b "#232831" -d "#e5e9f080" -e "#88c0d0" -s "#c5c8c626"
#albert &
unclutter -idle 2 -root &
dunst &
echo -e 'power on\nexit' | bluetoothctl
xrdb ~/.Xresources

# keybindings
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-a spawn ~/Projects/Launcher/launcher.py
hc keybind $Mod-d spawn bash -c "[ \$(herbstclient get_attr tags.focus.curframe_wcount) -gt 0 ] && saveclose $h || herbstclient remove"
hc keybind $Mod-Return spawn xterm
hc keybind $Mod-Shift-Return spawn xterm -e "\fff; cd \"\$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d" 2>/dev/null)\"; rm "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d" 2>/dev/null; bash"
hc keybind $Mod-Shift-v spawn xterm -e "vim"
hc keybind $Mod-Shift-m spawn xterm -e "herbstclient fullscreen on; \mocp -T /home/isaacelenbaas/dotfiles/mocp-theme"

# basic movement
hc keybind $Mod-h focus left
hc keybind $Mod-t focus down
hc keybind $Mod-c focus up
hc keybind $Mod-n focus right

# moving clients
hc keybind $Mod-Shift-h or / shift left / \
	chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-t shift down
hc keybind $Mod-Shift-c shift up
hc keybind $Mod-Shift-n or / shift right / \
	chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
hc keybind $Mod-apostrophe cycle 1
hc keybind $Mod-comma cycle -1

# splitting frames
#hc keybind $Mod-m chain , split bottom 0.5 , focus down  , spawn albert show
hc keybind $Mod-m chain , split bottom 0.5 , focus down
#hc keybind $Mod-s chain , split right  0.5 , focus right , spawn albert show
hc keybind $Mod-s chain , split right  0.5 , focus right

# resizing frames
resizestep=0.05
hc keybind $Mod-o      resize left  +$resizestep
hc keybind $Mod-e      resize down  +$resizestep
hc keybind $Mod-period resize up    +$resizestep
hc keybind $Mod-u      resize right +$resizestep

# layouting
hc keybind $Mod-f cycle_layout 1 max grid
hc keybind $Mod-Shift-f fullscreen toggle
hc keybind $Mod-space cycle_layout 1 vertical horizontal

# tag movement
hc keybind $Mod-l chain , use_index -$m , spawn updatedzen
hc keybind $Mod-BackSpace chain , use_index +$m , spawn updatedzen

hc keybind $Mod-y spawn bash -c 'herbstclient setenv clip $(herbstclient get_attr clients.focus.winid)'
hc keybind $Mod-i spawn bash -c 'herbstclient bring $(herbstclient getenv clip)'

# tags
tag_names=({1..12})
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
	hc add "${tag_names[$i]}"
done

# theme
hc attr theme.tiling.reset 1
hc set frame_border_normal_color '#2C2C2C'
hc set frame_border_active_color '#383838'

hc set always_show_frame 1
hc set frame_border_width 3
hc set frame_bg_transparent 1 # solid vs border frame

hc set window_gap 10

hc attr theme.border_width 3
hc attr theme.active.color '#009fbc'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color '#EF9C00'

hc attr theme.inner_width 1 # between border and window
hc attr theme.inner_color black

hc set frame_padding 0 # between inner and window

hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# rules
hc unrule -F

hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on #floating=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

#hc rule class='albert' floating=on #manage=off pseudotile=on
hc rule class='discord' tag=2
hc rule class='Steam' tag=3
hc rule class='mpv' title='noMin' fullscreen=on
hc rule class='mpv' not title='noMin' focus=off index='/'

# start
hc set tree_style '╾│ ├└╼─┐' # For printing window list
hc unlock
hc detect_monitors
killall dzen2
killall dzenbar
dzenbar $h | dzen2 -ta l -e '' -h $h -fn "DejaVu" -p

